---
output: 
  html_document:
    keep_md: true
---

# OSS RL Aug-Sep 2017 analysis on D36

```{r adjust_directory_if_needed, include=FALSE}
# Initialise Project
# Uncomment lines below if rmd file is placed in a subdirectory
# library(knitr)
# opts_knit$set(root.dir = normalizePath('../')) 
```

```{r load_project, include=FALSE}
# 1. Set options in config/global.dcf
# 2. Load packages listed in config/global.dcf
# 3. Import functions and coe in lib directory
# 4. Load data in data directory
# 5. Run data manipulations in munge directory 

rm(list = ls()) # optionally refresh workspace
library(ProjectTemplate); load.project()
rl_os <- subset(rl_os, month %in% c('y201708', 'y201709'))
rm(thaiMaps)
```

Test of independent (difference) : result & month
```{r chiq_test_independent_result_month, echo=FALSE}
group <- 'month'
attrib <- 'result'
t <- table(rl_os[[group]], rl_os[[attrib]])
cat(paste0('Table of ', attrib, ' by ', group))
print(t)
writeLines('')
cat(paste0('Percent contribution of ', attrib, ' by ', group))
prop.table(t, 1)*100
chisq.test(t)
i <- chisq.test(t)
i_p <- i$p.value
if (i_p <= 0.05) {
    cat(paste0(group,' and ',attrib, ' are dependent'))
} else {
    cat(paste0(group,' and ',attrib, ' are independent'))
}
# mosaicplot(t)
# assocplot(t)
rm(list = c('group', 'attrib', 't', 'i', 'i_p'))
```

Test of each result proportion by month
```{r prop_test_each_result_month, echo=FALSE}
all_result <- unique(rl_os$result)
for (i in seq_along(all_result)) {
    t <- table(rl_os$month, ifelse(rl_os$result == all_result[i], 
                                   all_result[i], paste0('Not ', all_result[i])))
        cat(paste0("Contingency Table of ", all_result[i]))
        print(t)
        cat("\n% Proportion")
        print(prop.table(t, 1)*100)
        print(prop.test(t))
}
rm(list = c('i', 't'))
```

From proportion test (z-test) of each *result*, the *D* effect the % approval rate most. Then do more test on each *D*

Number of top 5 *D*
```{r top5_d, echo=FALSE}
top5 <- rl_os %>%
        filter(result == 'D') %>%
        group_by(month, result_description) %>%
        summarise(n = n()) %>%
        spread(month, n) %>%
        top_n(5)
print(top5)
```

% Proportion of top 5 *D*
```{r per_top5_d, echo=FALSE}
rl_os %>%
    filter(result == 'D') %>%
    group_by(month, result_description) %>%
    summarise(n = n()) %>%
    mutate(per_finl = prop.table(n)*100) %>%
    select(month, result_description, per_finl) %>%
    spread(key = month, value = per_finl) %>%
    top_n(5)
```

Proportion test top 5 *D* by each *result description*
```{r test_top5_result_desc, echo=FALSE0}
top5_desc <- top5$result_description
d <- rl_os %>% filter(result == 'D')
for (i in seq_along(top5_desc)) {
    t <- table(d$month, ifelse(d$result_description == top5_desc[i], 
                                   top5_desc[i], paste0('Not ', top5_desc[i])))
        cat(paste0("Contingency Table of ", top5_desc[i]))
        print(t)
        cat("\n% Proportion")
        print(prop.table(t, 1)*100)
        print(prop.test(t))
}

```



